name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run prereport
          command: npm run cypress:ci:stg
        env:
          CYPRESS_API_URL_STG: ${ secrets.CYPRESS_API_URL_STG }
          CYPRESS_EMAIL_STG: ${ secrets.CYPRESS_EMAIL_STG }
          CYPRESS_PASSWORD_STG: ${ secrets.CYPRESS_PASSWORD_STG }